### ISSUE TITLE
Snes Duplicated input

### ISSUE THREAD

**Issue by anisiovalverde** [madcock/sf2000_multicore_cores#1]
On multicore my  B and A doing the same as A and Y and X doing the same as Y

**Comment by anisiovalverde** [comment]
Look like the emulator is taking the SFC buttons configuration in the snes core

**Comment by madcock** [comment]
Unfortunately that's a known problem. If you use the stock button remapping tool for any built-in emulator, it will break button mappings in multicore cores. That's why when installing a multicore alpha version we recommend (in the readme.txt) flashing a new firmware image for version 1.6 (or 1.71, since multicore install replaces the only changed file, bisrv.add.) Once installed, the button mapping settings should not be used or it will break the default mappings.

Multicore is still in a very early alpha state, and it may take some time for these sorts of features to be added. A few cores have button mapping definitions in their opt files (in /roms/config) which could be edited by hand or mapped using retroarch on another machine and copied over. But most cores currently don't have a way to remap buttons.

If you need to be able to remap buttons, best not to use multicore yet, and just use the original emulators in the official firmware.

**Comment by madcock** [comment]
Not planned as a feature for alpha version.
